# Allow tmux to use terminal colors
set-option -sa terminal-overrides ",xterm*:Tc"

# Turn on mouse support
set -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Place Tmux status bar at the top
set-option -g status-position top

# Reload config file 
bind r source-file ~/.config/tmux/tmux.conf

# Tmux theme
set -g @catppuccin_flavour 'mocha'

setw -g window-status-bell-style 'fg=yellow bg=red bold'

# messages
set -g message-style 'fg=yellow bg=red bold'

# Split panes horizontally using the % key
bind h split-window -h -c "#{pane_current_path}"

# Split panes vertically using the " key
bind v split-window -v -c "#{pane_current_path}"

# Open new windows in the same directory using the c key
bind c new-window -c "#{pane_current_path}"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dreamsofcode-io/catppuccin-tmux'

# Remap the prefix key
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
